points:
  - "1"
  - "2"
  - "3"
  - "5"
  - "8"
  - "13"
  - "20"
  - "40"
  - ":("
port: 8080
words:
  - "aliceblue"
  - "antiquewhite"
  - "aqua"
  - "aquamarine"
  - "azure"
  - "beige"
  - "bisque"
  - "black"
  - "blanchedalmond"
  - "blue"
  - "blueviolet"
  - "brown"
  - "burlywood"
  - "cadetblue"
  - "chartreuse"
  - "chocolate"
  - "coral"
  - "cornflowerblue"
  - "cornsilk"
  - "crimson"
  - "cyan"
  - "deeppink"
  - "deepskyblue"
  - "dimgray"
  - "dodgerblue"
  - "firebrick"
  - "floralwhite"
  - "forestgreen"
  - "fuchsia"
  - "gainsboro"
  - "ghostwhite"
  - "gold"
  - "goldenrod"
  - "gray"
  - "green"
  - "greenyellow"
  - "honeydew"
  - "hotpink"
  - "indianred"
  - "indigo"
  - "ivory"
  - "khaki"
  - "lavender"
  - "lavenderblush"
  - "lawngreen"
  - "lemonchiffon"
  - "lime"
  - "limegreen"
  - "linen"
  - "magenta"
  - "maroon"
  - "midnightblue"
  - "mintcream"
  - "mistyrose"
  - "moccasin"
  - "navajowhite"
  - "navy"
  - "oldlace"
  - "olive"
  - "olivedrab"
  - "orange"
  - "orangered"
  - "orchid"
  - "papayawhip"
  - "peachpuff"
  - "peru"
  - "pink"
  - "plum"
  - "powderblue"
  - "purple"
  - "red"
  - "rosybrown"
  - "royalblue"
  - "saddlebrown"
  - "salmon"
  - "sandybrown"
  - "seagreen"
  - "seashell"
  - "sienna"
  - "silver"
  - "skyblue"
  - "slateblue"
  - "slategray"
  - "snow"
  - "springgreen"
  - "steelblue"
  - "tan"
  - "teal"
  - "thistle"
  - "tomato"
  - "turquoise"
  - "violet"
  - "wheat"
  - "white"
  - "whitesmoke"
  - "yellow"
  - "yellowgreen"
